# Generated by Django 5.2.12 on 2026-04-20 00:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderType', models.CharField(choices=[('purchase', 'Покупка (в наличии)'), ('import', 'Заказ (под заказ у партнера)'), ('reservation', 'Предзаказ (бронь)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('assembly', 'Сборка'), ('in_transit', 'В доставке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('verification', 'Сверка позиций (Import)'), ('shipping_to_spb', 'Отправка Сайт СПБ (Import)'), ('notified', 'Уведомление клиента (Reservation)')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_method', models.CharField(blank=True, max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('assembled_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
            ],
        ),
    ]
