# Generated by Django 5.2.12 on 2026-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает оплаты'), ('assembly', 'Сборка'), ('in_transit', 'В доставке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('verification', 'Сверка позиций (Import)'), ('shipping_to_spb', 'Отправка Сайт СПБ (Import)'), ('notified', 'Уведомление клиента (Reservation)'), ('under_consideration', 'На рассмотрении (Reservation)')], max_length=30),
        ),
    ]
