# Generated by Django 5.2.12 on 2026-04-20 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='en', max_length=15)),
                ('quality', models.CharField(choices=[('NM', 'NM'), ('SP', 'SP'), ('HP', 'HP'), ('MP', 'MP'), ('DM', 'DM')], max_length=5)),
                ('foil', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='cards.card')),
            ],
        ),
    ]
