# Generated by Django 5.2.12 on 2026-04-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Colorless', 'Colorless'), ('Multicolor', 'Multicolor'), ('White', 'White'), ('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Green', 'Green')], max_length=15)),
                ('set_code', models.CharField(max_length=30)),
                ('set_name', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_number', models.CharField()),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_small', models.URLField(blank=True)),
                ('image_url_normal', models.URLField(blank=True)),
                ('image_url_large', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='cards_card_name_a125cc_idx'), models.Index(fields=['set_code'], name='cards_card_set_cod_d6cc57_idx')],
            },
        ),
    ]
